services:
  ad-dc:
    image: linuxcrafts/samba-ad-dc:latest
    container_name: samba-ad-dc
    cap_add:
      - SYS_ADMIN
    environment:
      - DNS_DOMAIN=example.local
      - ADMIN_PASSWORD=Admin@1234!
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - samba-data:/samba
    networks:
      - backend-network

  db:
    image: postgres:15-alpine
    container_name: ad-integration-db
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build: .
    container_name: ad-integration-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ad-dc
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  samba-data: