services:
  ad-dc:
    image: linuxcrafts/samba-ad-dc:latest
    container_name: samba-ad-dc
    cap_add:
      - SYS_ADMIN
    environment:
      - DNS_DOMAIN=EXAMPLE.LOCAL
      - ADMIN_PASSWORD=YourStrongPass
    ports:
      - "389:389" 
      - "636:636" 
      - "53:53/udp" 
    volumes:
      - samba-data:/samba
  db:
    image: postgres:15-alpine
    container_name: ad-integration-db
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/ddata
    networks: 
      - backend-network

  backend:
    build: .
    container_name: ad-integration-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ad-dc
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  samba-data: