name: CI pipeline for AD project 
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-and-push-ad-project:
    name: build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Down containers
        run: docker compose down

      - name: Build image
        run: docker compose build

      - name: Up containers
        run: docker compose up -d
