name: CI pipeline for AD project 
on:
  push:
    branches: 
      - main

  workflow_dispatch:

jobs:
  build-and-push-ad-project:
    name: build and push image
    runs_on: ubuntu_latest

    steps:
      - name: Cheking Repository
        uses: actions/checkout@v6.0.2

    - name: Docker Detup Buildx
      uses: docker/setup-buildx-action@v3.12.0

    - name: Down containers
      run: docker compose down
